// <auto-generated />
using System;
using IdeasClinicInventory.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdeasClinicInventory.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710194002_AddUntrackedUnits")]
    partial class AddUntrackedUnits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IdeasClinicInventory.Web.Models.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedUseType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("QuantityReservedForAdmins")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceImagePath")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("RestrictedToAdmins")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CatalogItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CatalogItems_Name_NotBlank", "LEN(LTRIM(RTRIM([Name]))) > 0");

                            t.HasCheckConstraint("CK_CatalogItems_QuantityReservedForAdmins_NonNegative", "[QuantityReservedForAdmins] >= 0");
                        });
                });

            modelBuilder.Entity("IdeasClinicInventory.Web.Models.InventoryLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ReferenceImagePath")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StorageUnitCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StorageUnitLevel")
                        .HasColumnType("int");

                    b.Property<string>("Subunit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RoomCode", "StorageUnitLevel", "StorageUnitCode", "Subunit")
                        .IsUnique();

                    b.ToTable("InventoryLocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryLocations_StorageUnitLevel_NonNegative", "[StorageUnitLevel] >= 0");
                        });
                });

            modelBuilder.Entity("IdeasClinicInventory.Web.Models.TrackedUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogItemId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HomeLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("HomeLocationId");

                    b.HasIndex("CatalogItemId", "Identifier")
                        .IsUnique();

                    b.ToTable("TrackedUnits", null, t =>
                        {
                            t.HasCheckConstraint("CK_TrackedUnits_Identifier_NotBlank", "LEN(LTRIM(RTRIM([Identifier]))) > 0");
                        });
                });

            modelBuilder.Entity("IdeasClinicInventory.Web.Models.UntrackedUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogItemId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("QuantityAtLocation")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("CatalogItemId", "LocationId")
                        .IsUnique();

                    b.ToTable("UntrackedUnits", null, t =>
                        {
                            t.HasCheckConstraint("CK_UntrackedUnits_QuantityAtLocation_NonNegative", "[QuantityAtLocation] >= 0");
                        });
                });

            modelBuilder.Entity("IdeasClinicInventory.Web.Models.TrackedUnit", b =>
                {
                    b.HasOne("IdeasClinicInventory.Web.Models.CatalogItem", "CatalogItem")
                        .WithMany("TrackedUnits")
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdeasClinicInventory.Web.Models.InventoryLocation", "HomeLocation")
                        .WithMany("TrackedUnits")
                        .HasForeignKey("HomeLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("HomeLocation");
                });

            modelBuilder.Entity("IdeasClinicInventory.Web.Models.UntrackedUnit", b =>
                {
                    b.HasOne("IdeasClinicInventory.Web.Models.CatalogItem", "CatalogItem")
                        .WithMany("UntrackedUnits")
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdeasClinicInventory.Web.Models.InventoryLocation", "Location")
                        .WithMany("UntrackedUnits")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("IdeasClinicInventory.Web.Models.CatalogItem", b =>
                {
                    b.Navigation("TrackedUnits");

                    b.Navigation("UntrackedUnits");
                });

            modelBuilder.Entity("IdeasClinicInventory.Web.Models.InventoryLocation", b =>
                {
                    b.Navigation("TrackedUnits");

                    b.Navigation("UntrackedUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
